# vim: ft=python

Import('env', 'lowl')

import os

pylowl = env.DistutilsBuildExt('pylowl', 'pylowl', deps=[lowl, 'lowl.pxd'])
env.Alias('pylowl', pylowl)

test_env = env.Clone()
test_env.Append(ENV = {'LD_LIBRARY_PATH': lowl[0].dir.abspath})
run_tests = test_env.NoTargetLocalRunner('pylowl-tests',
    'python -m doctest --doctest-extension=pyx -v pylowl.pyx'.split(),
    [pylowl, 'pylowl.pyx'])

install_pylowl = env.DistutilsInstall('pylowl-install', pylowl, args=['--user'])

Return('pylowl')
