# Enchanted plotting scroll for particle filter experiments on LDA,
# geared toward the 3-category subsets diff3, rel3, and sim3
# of the 20 newsgroups dataset.  (However, shouldn't be too hard to
# adapt to other datasets.)
#
# Generates each plot from several input files.  Each file corresponds
# to the aggregated traces of a given evaluation metric (e.g., in-sample
# NMI, out-of-sample NMI, out-of-sample perplexity, out-of-sample
# coherence) from several particle filter runs, and is assumed to be
# tab-formatted.  Specifically, we expect each file to look something
# like the following:
#
# iter	run.0	run.1	run.2	run.3	run.4
# 0	0.0	0.0	0.0	0.0	0.0
# 50	0.2	0.35	0.2	0.12	0.3
# 100	0.25	0.35	0.22	0.3	0.37
# 150	0.28	NA	0.27	0.39	0.4
# [...]
#
# Where columns correspond to different particle filter runs, rows
# correspond to iterations of the particle filter---each entry in a
# given row should correspond to the *same* iteration---and NA values
# are handled gracefully, and can be used to indicate log-parsing
# errors or (more likely) premature termination of a run.
#
# The particle filter code itself lives in littleowl/apps/lda.  In the
# following, we refer to revision
# a8e4d161306f3f079cc25ac6c8a9647bc9d3feda of littleowl as it is known
# to work.
#
# The tab files mentioned previously can be generated by running the
# particle filter several times and dumping each run's output to
# a separate file, organized in a hierarchical fashion as follows:
# 1-rs1k/
#     diff3/
#         1.log
#         2.log
#         [...]
#     rel3/
#         1.log
#         2.log
#         [...]
#     sim3/
#         1.log
#         2.log
#         [...]
# 20-rs10k/
#     diff3/
#         1.log
#         2.log
#         [...]
#     rel3/
#         1.log
#         2.log
#         [...]
#     sim3/
#         1.log
#         2.log
#         [...]
# [...]
# Here we show the output directories for two experiments, 20-rs1k
# and 20-rs10k.  Particle filters were run on each of three datasets
# diff3, rel3, and sim3 for each experiment.  The log files for the
# first two runs are shown.
#
# The scripts in littleowl/apps/lda/experiments launch particle
# filter simulations on the grid and produce the aforementioned
# output hierarchies.
#
# Once the log files are generated, the script
# littleowl/apps/lda/extract_log_stats.py can be used to ingest
# all of the log files within an experiment directory and produce the
# desired tab-formatted input files for this script/enchanted plotting
# scroll.  E.g.,
#
# $ python extract_log_stats.py 20-rs1k
#
# will read all of the log files nested in the 20-rs1k directory and
# write .tab files in that directory.  If the experiment directories
# are in the current directory then we can (finally) generate the plots
# for the paper as follows:
#
# $ pwd
# .../littleowl/apps/lda
# $ R --vanilla -f plot_log_stats.r
# [...]
# $ ls plots
# 20_out_of_sample_nmi.png

library(ggplot2)
library(gridExtra)
library(data.table)

options(warn=1)

# The following function downloaded on 2014-03-12 from
# https://github.com/hadley/ggplot2/wiki/Share-a-legend-between-two-ggplot2-graphs
g_legend <- function(a.gplot) {
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
}

dirpath.in <- '.'
dirpath.out <- 'plots'

plot.raw <- function(d, dataset.name) {
    return(ggplot(aes(x=iter, y=val, group=run, color=experiment), data=d) +
        geom_line(alpha=0.3, size=0.5) +
        theme_bw() +
        ggtitle(dataset.name) +
        ylab('NMI') +
        xlab('document'))
}

plot.smooth <- function(d, dataset.name) {
    return(ggplot(aes(x=iter, y=val, group=experiment, color=experiment, fill=experiment), data=d) +
        stat_summary(fun.data=mean_sdl, geom='smooth', mult=1, size=1) +
        (if (!all(is.na(d$val.eb))) {
                stat_summary(aes(x=iter, y=val.eb), fun.data=mean_sdl, geom='errorbar', mult=1, size=1)
            } else {
                NULL
            }) +
        theme_bw() +
        ggtitle(dataset.name) +
        ylab('NMI (mean +/- stdev)') +
        xlab('document'))
}

plot.tng3 <- function(d, plot.fun) {
    p.diff3 <- plot.fun(subset(d, dataset == 'diff3'), 'diff3')
    p.rel3 <- plot.fun(subset(d, dataset == 'rel3'), 'rel3')
    p.sim3 <- plot.fun(subset(d, dataset == 'sim3'), 'sim3')

    legend <- g_legend(p.diff3)

    grid.arrange(
        p.diff3 + theme(legend.position='none'),
        p.rel3 + theme(legend.position='none'),
        p.sim3 + theme(legend.position='none'),
        legend,
        nrow=2)
}

plot.null <- function(d, plot.fun) {
    p.null <- plot.fun(d, 'null')
    plot(p.null)
}

plot.experiments <- function(experiment.group.name, dataset.names, experiment.names, experiment.names.legend, stat.names, stat.names.legend, plot.fun, plot.width, plot.height) {
    if (is.null(stat.names.legend)) {
        stat.names.legend <- stat.names
    }
    if (is.null(experiment.names.legend)) {
        experiment.names.legend <- experiment.names
    }
    if (is.null(plot.width)) {
        plot.width <- 5
    }
    if (is.null(plot.height)) {
        plot.height <- 5
    }

    d.list <- list()

    cat(experiment.group.name, '\n')
    for (dataset.name in dataset.names) {
        cat('*', dataset.name, '\n')

        for (k in 1:length(stat.names)) {
            stat.name <- stat.names[k]
            stat.name.legend <- stat.names.legend[k]
            for (i in 1:length(experiment.names)) {
                experiment.name <- experiment.names[i]
                experiment.name.legend <- experiment.names.legend[i]
                cat('  -', experiment.name, stat.name, '\n')
                filename.in <- paste(dirpath.in, '/', experiment.name, '/',
                    dataset.name, '_', stat.name, '.tab', sep='')
                data.raw <- tryCatch(read.table(filename.in, header=T),
                    error=function(ex) {NULL})
                if (! is.null(data.raw)) {
                    data.raw.idx <- apply(data.raw, 1,
                        function(r) { !all(is.na(r)) })
                    data.raw <- data.raw[data.raw.idx,]
                    num.nonempty.iters <- dim(data.raw)[1]
                    for (j in 2:dim(data.raw)[2]) {
                        val <- data.raw[,j]
                        val.eb <- if (num.nonempty.iters == 1) {
                                val
                            } else {
                                rep(NA, num.nonempty.iters)
                            }
                        d.list[[length(d.list)+1]] <- data.frame(
                            iter=data.raw[,1],
                            val=data.raw[,j],
                            val.eb=val.eb,
                            experiment=rep(experiment.name.legend, num.nonempty.iters),
                            dataset=rep(dataset.name, num.nonempty.iters),
                            run=rep(paste(dataset.name, stat.name, experiment.name, as.character(j), sep='/'), num.nonempty.iters),
                            stat=rep(stat.name.legend, num.nonempty.iters))
                    }
                }
            }
        }
    }

    d <- rbindlist(d.list)

    if (length(dim(d)) > 0 && dim(d)[1] > 0) {
        dir.create(dirpath.out)

        for (j in 1:length(stat.names)) {
            d.subset <- subset(d, stat == stat.names.legend[j])

            filename.out <- paste(dirpath.out, paste(experiment.group.name, '_', stat.names[j], '.png', sep=''), sep='/')
            png(filename.out, width=plot.width, height=plot.height, pointsize=11, res=300, units='in')
            plot.fun(d.subset, plot.smooth)
            dev.off()

            filename.out <- paste(dirpath.out, paste(experiment.group.name, '_', stat.names[j], '_raw.png', sep=''), sep='/')
            png(filename.out, width=plot.width, height=plot.height, pointsize=11, res=300, units='in')
            plot.fun(d.subset, plot.raw)
            dev.off()
        }
    } else {
        cat('Data empty for', experiment.group.name, '\n')
    }
}

metrics <- c('out_of_sample_perplexity')
metrics.legend <- c('out-of-sample perplexity')

#plot.experiments('1', c('diff3', 'rel3', 'sim3'), c('1-rs0', '1-rs1k', '1-rs500k'), c('no rejuvenation', 'reservoir size 1k', 'full uniform rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('2', c('diff3', 'rel3', 'sim3'), c('2-rs1k-ibs0', '2-rs1k-ibs30', '2-rs1k-ibs100', '2-rs1k-ibs300', '2-rs1k-ibs3k'), c('no initialization', 'initialization size 30', 'initialization size 100', 'initialization size 300', 'batch gibbs'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('2_3_4', c('diff3', 'rel3', 'sim3'), c('4', '3', '2-rs1k-ibs100'), c('no resample/rejuv', 'resample', 'resample and rejuv'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('5', c('diff3', 'rel3', 'sim3'), c('5-ess5', '5-ess10', '5-ess20', '5-ess40'), c('ess 5', 'ess 10', 'ess 20', 'ess 40'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('6_3', c('diff3', 'rel3', 'sim3'), c('3', '6-rs10k-rss10', '6-rs10k-rss30', '6-rs10k-rss100', '6-rs10k-rss300', '6-rs10k-rss1k'), c('no rejuv', 'rejuv size 10', 'rejuv size 30', 'rejuv size 100', 'rejuv size 300', 'rejuv size 1k'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('8', c('diff3', 'rel3', 'sim3'), c('8-t2', '8-t3', '8-t4', '8-t5', '8-t6'), c('num topics 2', 'num topics 3', 'num topics 4', 'num topics 5', 'num topics 6'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('9', c('diff3', 'rel3', 'sim3'), c('9-rs1k-ibs0', '9-rs1k-ibs10', '9-rs1k-ibs30', '9-rs1k-ibs100', '9-rs1k-ibs300', '9-rs1k-ibs1k', '9-rs1k-ibs3k'), c('no initialization', 'initialization size 10', 'initialization size 30', 'initialization size 100', 'initialization size 300', 'initialization size 1k', 'initialization size 3k'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('10', c('diff3', 'rel3', 'sim3'), c('10-rs1k-ibs0', '10-rs1k-ibs10', '10-rs1k-ibs30', '10-rs1k-ibs100', '10-rs1k-ibs300', '10-rs1k-ibs1k', '10-rs1k-ibs3k'), c('no initialization', 'initialization size 10', 'initialization size 30', 'initialization size 100', 'initialization size 300', 'initialization size 1k', 'initialization size 3k'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('2_9_10', c('diff3', 'rel3', 'sim3'), c('2-rs1k-ibs100', '9-rs1k-ibs100', '10-rs1k-ibs100'), c('untuned init', 'nmi-tuned init', 'perplexity-tuned init'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('11', c('null'), c('11-t3', '11-t6', '11-t12'), c('num topics 3', 'num topics 6', 'num topics 12'), c('out_of_sample_perplexity'), c('out-of-sample perplexity'), plot.tng3, NULL, NULL)
#plot.experiments('12', c('null'), c('12-rs1k-ibs0', '12-rs1k-ibs10', '12-rs1k-ibs30', '12-rs1k-ibs100', '12-rs1k-ibs300', '12-rs1k-ibs1k', '12-rs1k-ibs3k'), c('no initialization', 'initialization size 10', 'initialization size 30', 'initialization size 100', 'initialization size 300', 'initialization size 1k', 'initialization size 3k'), c('out_of_sample_perplexity'), c('out-of-sample perplexity'), plot.tng3, NULL, NULL)
#plot.experiments('13', c('null'), c('13-rs0', '13-rs10', '13-rs100', '13-rs1k', '13-rs10k'), c('no rejuvenation', 'reservoir size 10', 'reservoir size 100', 'reservoir size 1k', 'reservoir size 10k'), c('out_of_sample_perplexity'), c('out-of-sample perplexity'), plot.tng3, NULL, NULL)
#plot.experiments('14', c('diff3', 'rel3', 'sim3'), c('14'), c('(ltr)'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('15', c('diff3', 'rel3', 'sim3'), c('15-rs1k-a0.001', '15-rs1k-a0.01', '15-rs1k-a0.1', '15-rs1k-a1', '15-rs1k-a10'), c('alpha 0.001', 'alpha 0.01', 'alpha 0.1', 'alpha 1', 'alpha 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('16', c('diff3', 'rel3', 'sim3'), c('16-rs1k-b0.001', '16-rs1k-b0.01', '16-rs1k-b0.1', '16-rs1k-b1', '16-rs1k-b10'), c('beta 0.001', 'beta 0.01', 'beta 0.1', 'beta 1', 'beta 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('17', c('diff3', 'rel3', 'sim3'), c('17-rs0', '17-rs1k', '17-rs500k'), c('no rejuvenation', 'reservoir size 1k', 'full uniform rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('18', c('diff3', 'rel3', 'sim3'), c('18-rs0', '18-rs1k', '18-rs500k'), c('no rejuvenation', 'reservoir size 1k', 'full uniform rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('19', c('diff3', 'rel3', 'sim3'), c('19-rs0', '19-rs1k', '19-rs500k'), c('no rejuvenation', 'reservoir size 1k', 'full uniform rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('20', c('diff3', 'rel3', 'sim3'), c('20-rs0', '20-rs1k', '20-rs500k'), c('no rejuvenation', 'reservoir size 1k', 'full uniform rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('21', c('diff3', 'rel3', 'sim3'), c('21-rs0', '21-rs1k', '21-rs500k'), c('no rejuvenation', 'reservoir size 1k', 'full uniform rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('22', c('diff3', 'rel3', 'sim3'), c('22'), c('gibbs (csg init docs)'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('23', c('diff3', 'rel3', 'sim3'), c('23'), c('gibbs (200 init docs)'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('24', c('diff3', 'rel3', 'sim3'), c('24'), c('gibbs (100 init docs)'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('25', c('diff3', 'rel3', 'sim3'), c('25-rs0'), c('no rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('27-rs0', c('diff3', 'rel3', 'sim3'), c('27-rs0'), c('no rejuvenation'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('27-rs1k', c('diff3', 'rel3', 'sim3'), c('27-rs1k'), c('reservoir size 1k'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('28', c('diff3'), c('28-rs50000-rss5000', '28-rs100000-rss10000', '28-rs500000-rss50000'), c('reservoir size 50k', 'reservoir size 100k', 'reservoir size 500k'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('29-a0.001', c('diff3'), c('29-a0.001-b0.001', '29-a0.001-b0.01', '29-a0.001-b0.1', '29-a0.001-b1', '29-a0.001-b10'), c('alpha 0.001, beta 0.001', 'alpha 0.001, beta 0.01', 'alpha 0.001, beta 0.1', 'alpha 0.001, beta 1', 'alpha 0.001, beta 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('29-a0.01', c('diff3'), c('29-a0.01-b0.001', '29-a0.01-b0.01', '29-a0.01-b0.1', '29-a0.01-b1', '29-a0.01-b10'), c('alpha 0.01, beta 0.001', 'alpha 0.01, beta 0.01', 'alpha 0.01, beta 0.1', 'alpha 0.01, beta 1', 'alpha 0.01, beta 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('29-a0.1', c('diff3'), c('29-a0.1-b0.001', '29-a0.1-b0.01', '29-a0.1-b0.1', '29-a0.1-b1', '29-a0.1-b10'), c('alpha 0.1, beta 0.001', 'alpha 0.1, beta 0.01', 'alpha 0.1, beta 0.1', 'alpha 0.1, beta 1', 'alpha 0.1, beta 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('29-a1', c('diff3'), c('29-a1-b0.001', '29-a1-b0.01', '29-a1-b0.1', '29-a1-b1', '29-a1-b10'), c('alpha 1, beta 0.001', 'alpha 1, beta 0.01', 'alpha 1, beta 0.1', 'alpha 1, beta 1', 'alpha 1, beta 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('29-a10', c('diff3'), c('29-a10-b0.001', '29-a10-b0.01', '29-a10-b0.1', '29-a10-b1', '29-a10-b10'), c('alpha 10, beta 0.001', 'alpha 10, beta 0.01', 'alpha 10, beta 0.1', 'alpha 10, beta 1', 'alpha 10, beta 10'), metrics, metrics.legend, plot.tng3, NULL, NULL)
#plot.experiments('30', c('diff3'), c('30-rs1k', '30-rs10k', '30-rs100k', '30-rs500k'), c('reservoir size 1k', 'reservoir size 10k', 'reservoir size 100k', 'reservoir size 500k'), metrics, metrics.legend, plot.tng3, NULL, NULL)
plot.experiments('32', c('null'),
    c('32-p10-t50-rs1k-rss100-a0.1-b0.1',
        '32-p1-t100-rs1k-rss100-a0.1-b0.1',
        '32-p1-t10-rs1k-rss100-a0.1-b0.1',
        '32-p1-t50-rs10k-rss1k-a0.1-b0.1',
        '32-p1-t50-rs1k-rss100-a0.1-b0.1',
        '32-p1-t50-rs1k-rss10-a0.01-b0.01',
        '32-p1-t50-rs1k-rss10-a0.01-b0.1',
        '32-p1-t50-rs1k-rss10-a0.1-b0.01',
        '32-p1-t50-rs1k-rss10-a0.1-b0.1'),
    NULL, metrics, metrics.legend, plot.null, 8, 6)
plot.experiments('33', c('null'),
    c('33-p10-t50-rs1k-rss100-a0.1-b0.1',
        '33-p1-t100-rs1k-rss100-a0.1-b0.1',
        '33-p1-t10-rs1k-rss100-a0.1-b0.1',
        '33-p1-t50-rs10k-rss1k-a0.1-b0.1',
        '33-p1-t50-rs1k-rss100-a0.1-b0.1',
        '33-p1-t50-rs1k-rss10-a0.01-b0.01',
        '33-p1-t50-rs1k-rss10-a0.01-b0.1',
        '33-p1-t50-rs1k-rss10-a0.1-b0.01',
        '33-p1-t50-rs1k-rss10-a0.1-b0.1'),
    NULL, metrics, metrics.legend, plot.null, 8, 6)
plot.experiments('34', c('null'),
    c('34-p10-t50-rs1k-rss100-a0.1-b0.1',
        '34-p1-t100-rs1k-rss100-a0.1-b0.1',
        '34-p1-t10-rs1k-rss100-a0.1-b0.1',
        '34-p1-t50-rs10k-rss1k-a0.1-b0.1',
        '34-p1-t50-rs1k-rss100-a0.1-b0.1',
        '34-p1-t50-rs1k-rss10-a0.01-b0.01',
        '34-p1-t50-rs1k-rss10-a0.01-b0.1',
        '34-p1-t50-rs1k-rss10-a0.1-b0.01',
        '34-p1-t50-rs1k-rss10-a0.1-b0.1'),
    NULL, metrics, metrics.legend, plot.null, 8, 6)
