# vim: ft=python


Import('env', 'lowl', 'pylowl', 'lowl_env', 'pylowl_env', 'write_run_sh')


Help('''
        pflda           Build pflda
        pflda-install   Install pflda
'''.lstrip('\r\n'))


pflda = env.DistutilsBuildExt('core', 'core', deps=[pylowl, 'pylowl.pxd', Glob('*.py'), Glob('*.r'), Glob('*.sh'), Glob('*.qsub'), Glob('experiments/*.sh')])
env.Alias('pflda', pflda)

install_pflda = env.DistutilsInstall('pflda-install', pflda, deps=['pflda_run_pf', 'pflda_run_gibbs', 'data.py', '__init__.py'])

run_sh = env.Command('run.sh', [], write_run_sh)
env.Alias('pflda-run-sh', run_sh)
