# vim: ft=python


Import('env', 'pylowl')


Help('''
        pflda           Build pflda
        pflda-install   Install pflda
'''.lstrip('\r\n'))


pflda = env.DistutilsBuildExt('pflda', 'pflda', deps=[pylowl, 'pylowl.pxd'])
env.Alias('pflda', pflda)

install_pflda = env.DistutilsInstall('pflda-install', pflda)
