# vim: ft=python


Import('env', 'lowl', 'pylowl')


Help('''
        pflda           Build pflda
        pflda-fat       Build pflda, copy dependencies into build dir
        pflda-install   Install pflda
'''.lstrip('\r\n'))


pflda = env.DistutilsBuildExt('pflda/core', 'pflda/core', deps=[pylowl, 'pylowl.pxd', Glob('*.py'), Glob('*.r'), Glob('*.sh'), Glob('*.qsub'), Glob('experiments/*.sh'), Glob('pflda/*.py'), 'pflda_run_pf', 'pflda_run_gibbs'])
env.Alias('pflda', pflda)

pflda_fat_lowl = env.Command(lowl[0].name, lowl, Copy('$TARGET', '$SOURCE'))
pflda_fat_pylowl = env.Command(pylowl[0].name, pylowl, Copy('$TARGET', '$SOURCE'))
pflda_fat = env.Alias('pflda-fat', [pflda_fat_lowl, pflda_fat_pylowl, pflda])

install_pflda = env.DistutilsInstall('pflda-install', pflda, deps=['pflda_run_pf', 'pflda_run_gibbs', 'data.py', '__init__.py'])
