# vim: ft=python

Import('env')
Export('env')

env.Append(CCFLAGS=['-O0', '-g', '-Wall', '-Wextra', '-std=gnu99'])

sources = [
    'lowl_sample.c',
    'lowl_hash.c',
    'lowl_math.c',
    'lowl_sketch.c',
    'lowl_types.c',
    'lowl_vectors.c',
]

lowl = env.SharedLibrary(target='lowl', source=sources, LIBS=['m'])
env.Alias('lowl-lib', lowl)
tests = env.Program(target='tests', source=['tests.c'], LIBS=['lowl', 'm'],
    LIBPATH='.')
env.Alias('lowl-tests', tests)

Return('lowl')
