# vim: ft=python


Import('env', 'lowl', 'pylowl')


Help('''
        bglda           Build bglda
        bglda-install   Install bglda
'''.lstrip('\r\n'))


bglda = env.DistutilsBuildExt('core', 'core', deps=[pylowl, 'pylowl.pxd', Glob('*.py'), 'bglda_run'])
env.Alias('bglda', bglda)

install_bglda = env.DistutilsInstall('bglda-install', bglda, deps=['bglda_run', 'data.py', '__init__.py'])
