# vim: ft=python


Import('env', 'lowl', 'pylowl', 'lowl_env', 'pylowl_env', 'write_run_sh')


Help('''
        bglda           Build bglda
        bglda-install   Install bglda
'''.lstrip('\r\n'))


run_sh = env.Command('run.sh', [], write_run_sh)

bglda = env.DistutilsBuildExt('core', 'core', deps=[pylowl, 'pylowl.pxd', Glob('*.py'), 'bglda_run', run_sh])
env.Alias('bglda', bglda)

install_bglda = env.DistutilsInstall('bglda-install', bglda, deps=['bglda_run', 'data.py', '__init__.py'])
