# vim: ft=python


Import('env')
Export('env')


lowl, install_lowl = env.SConscript('lowl/SConscript')
Export('lowl', 'install_lowl')

pylowl, install_pylowl = env.SConscript('pylowl/SConscript')
Export('pylowl', 'install_pylowl')

env.SConscript('proj/SConscript')
