# vim: ft=python


Import('env')
Export('env')


Help('''
        install         Install lowl and pylowl
'''.lstrip('\r\n'))


lowl, install_lowl = env.SConscript('lowl/SConscript')
Export('lowl', 'install_lowl', 'lowl_env')

pylowl, install_pylowl = env.SConscript('pylowl/SConscript')
Export('pylowl', 'install_pylowl', 'pylowl_env')

install = Alias('install', [install_lowl, install_pylowl])

env.SConscript('proj/SConscript')
